### ISSUE TITLE
批量重命名界面疑似Bug

### ISSUE THREAD

**Issue by hhhhdmy** [ourongxing/ohmymn#10]
开发者你好！非常感谢你开发了一个这么好用的插件！这几天用下来感觉原地起飞爽死了！！！
目前遇到一个bug是，iPad版本批量重命名标题后弹出的对话框，无法使用外接键盘的左右方向键调整光标，而会移动后面的脑图画布。。。我不大清楚这个是插件的bug还是MN的bug，毕竟要在框内输入正则表达式，您看看能不能解决呢？麻烦啦！

**Comment by ourongxing** [comment]
暂时无法解决这个问题，不过你只需要点一下输入框就能使用方向键来移动光标了
