### ISSUE TITLE
功能建议：摘录锁定

### ISSUE THREAD

**Issue by ceranyi** [ourongxing/ohmymn#11]
首先感谢大佬的付出😄，太厉害了！

需求：有时摘录一段文字后，因文字内容有错误或文字内容过于冗余，需要对其进行更改。更改完成后，常常因为文档中摘录选区的再调整（大部分是因为误触），使得摘录内容又变回原样。所以，有没有办法既保留文档的摘录选区，又能锁定脑图的摘录内容，使得脑图的摘录内容不因选区的调整而发生改变？

因为不懂编程，所以也不知道这个功能有没有可行性，难度大不大。再次谢谢！

**Comment by ourongxing** [comment]
确实，我也经常有这种困扰，锁定文字是可以实现的，小 case。
