### ISSUE TITLE
大佬你好可不可以等你考研完做一个可以更改摘录字体的插件呢:)

### ISSUE THREAD

**Issue by Leonllv** [ourongxing/ohmymn#15]
1.需求：就功能而言就类似于一件更改摘录里面所有的颜色那种，选中后将摘录里面的字体更改为某一种字体
2.原因：有时候看多了某一种字体就习惯了，是我个人的不情之请，这个也没什么大不了的只是就我个人而言(｡ì _ í｡)
3.优先级：等大佬考研完再弄吧，这个我不清楚难度，看社区另一位开发者说法说是很难

**Comment by ourongxing** [comment]
无法实现
