### ISSUE TITLE
摘录自动合并为标题功能bug

### ISSUE THREAD

**Issue by clark874** [ourongxing/ohmymn#16]
创作者好，感谢你最新的更新，实现了摘录标题自动化生成的功能！

目前使用中出现一个问题：即在只打开“摘录自动合并为标题”功能，却不打开“是单词”和“不含有点号”功能的时候，采用拖拽方式将文本拖入摘录的时候，文本无法自动转化为标题链。只有在打开上述两个功能的时候，才能实现拖拽转文本自动转化标题链的功能。

不知道这是否是一个bug？

希望创作者再接再厉！

**Comment by ourongxing** [comment]
本身就是要满足成为标题的条件才行，你可以设置最少字数，也可以使用自定义，自定义的优先级最高

**Comment by clark874** [comment]
也就是说，我需要在拖拽的文本必须符合标题的三个条件：要么单词，要么没有点号，要么符合我自身定义的条件，否则拖拽就没有转化效果。

谢谢创作者解答！

**Comment by clark874** [comment]
继续汇报一个问题：我采用了`(/^(.*){1,3}$/, "$1")`的正则表达式，关闭单词和点号，这种情况下我的理解是摘录文本如果大于3个字就生成摘录，如果小于3个字就生成标题链并删除摘录内容。但实际操作上，摘录一段十个字的话还是形成了标题链并删除了摘录。请问这是为什么呢？

**Comment by ourongxing** [comment]
应该这样写 `(/^.{1,3}$/, "$&")`

**Comment by ourongxing** [comment]
可能是我文档有所误导

**Comment by clark874** [comment]
非常感谢！
