### ISSUE TITLE
与OCR Pro不兼容

### ISSUE THREAD

**Issue by Delayless** [ourongxing/ohmymn#18]
AutoComplete用来做英语阅读真的太棒了，感谢开发者。

反馈两个使用这一功能中遇到的两个小问题：
1. 如果开启了OCR Pro自动在线校正功能的话绝大多数时候自动填充完中文释义又会消失。如果插件能与OCR pro兼容会更完美
2. 没有手动执行填充单词解释/词频（中文释义）的功能，这一功能应该也可以曲线救国解决问题一。
3. 暂时发现副词没办法翻译（填充单词解释，词频）

**Comment by ourongxing** [comment]
我也是郁闷，我文档写的这么好，不会看嘛，是否开启自动矫正，这个开关你开了吗

**Comment by ourongxing** [comment]
补全词型本来就包括了填充解释和词频，这就是一个模块里面的，只要你开了开关就会同时执行。补全副词，无法实现，这不是我想补全就能补全的。

**Comment by Delayless** [comment]
文档我是看了的，也知道是MN官方不开放API所以你才暂时没法优化。

明白了，你发的帖子基本都看了，期待官方能够在这方面多做点事吧。

**Comment by ourongxing** [comment]
你有毒吧，ohmymn 是目前唯一一个优化了自动矫正和自动 OCR 的插件

**Comment by ourongxing** [comment]
![Screenshot_20210909-082840.jpg](https://user-images.githubusercontent.com/48356807/132602992-32163799-3f5c-4e03-9440-1495cfbb2881.jpg)
