### ISSUE TITLE
功能建议：全局顶部开关

### ISSUE THREAD

**Issue by wslldsdhii** [ourongxing/ohmymn#23]
希望在插件最上层添加一排小图标，对应下面功能中的摘录时自动执行的开关。
并且增加一个，一键关闭 和 一键恢复上次开启过 两个按钮。
这样就不用每次去翻页查找。
希望，控制界面可以做的更小一点，或者可以增加用户自定义调整大小。例如拖拽按比例调整。

最后感谢开发者的努力和共享。
最后希望以后可以按到正则表达式进行 搜索的插件可以出现。官方搜索，太难用了。

**Comment by ourongxing** [comment]
用 js 来使用 uikit 限制太多了，而且很多不支持，目前已经是我经过很多次尝试后可以实现的最佳效果，这不是原生开发，没办法实现复杂的效果。
