### ISSUE TITLE
反馈建议：希望增加内置词典，自动填充词义可从内置的权威词典添加

### ISSUE THREAD

**Issue by u2003** [ourongxing/ohmymn#24]
onmymn现在可以填充词义的功能确实比较方便了，但是希望可以内置权威的词典，如朗文、柯林斯、牛津等等的mdx格式的词典，在释义的丰富性和准确性上优势极大。如果制作过程需要优质词典库经过作者同意我可以无偿提供，自己通过论坛等渠道收集了不少了。
觉得比较有实现的可能，因为已经有插件把mdx词典集成到mn的插件里了
放上几张柯林斯、朗文等等权威词典的截图
<img width="597" alt="image" src="https://user-images.githubusercontent.com/84957135/140597409-3230270a-0d13-4c41-81b9-8a8780dc32f4.png">
<img width="588" alt="image" src="https://user-images.githubusercontent.com/84957135/140597416-2a10a790-ebaf-4f30-92ff-de9939a8dd68.png">
<img width="528" alt="image" src="https://user-images.githubusercontent.com/84957135/140597420-abbf9651-e323-45ed-95f6-b66759242f82.png">
<img width="590" alt="image" src="https://user-images.githubusercontent.com/84957135/140597426-a0f81f86-5c75-4e9e-9922-b6ffb9d0f94c.png">
<img width="582" alt="image" src="https://user-images.githubusercontent.com/84957135/140597438-2e547285-c7ab-4535-8fe1-057f436b922e.png">
<img width="590" alt="image" src="https://user-images.githubusercontent.com/84957135/140597443-6e52b207-7bfd-4cf0-a9cd-53be51b03e1b.png">

**Comment by u2003** [comment]
非常希望ohmymn和mdxdict两个插件的优势可以集成在一起，对于学习外语实在是太方便、帮助太大了！！！

**Comment by ourongxing** [comment]
你看看 mdxdict 的大小，以及把 mn 的启动速度拖慢了多少，ohmymn 不会也不可能做这个功能。
