### ISSUE TITLE
关于标题别名的建议

### ISSUE THREAD

**Issue by u2003** [ourongxing/ohmymn#28]
目前ohmymn可以给英文单词自动补全词形作为标题别名，也可以通过AnotherAutoTitle插件把符合条件的摘录转换成标题别名。但是在一些外文/专业书籍里的专业名词，自动补全词形里的词汇量不能够涵盖到，而文章里也没有它的别名，只能从维基/Google/欧路词典里面把相应的中文/英文/其它外文的对应概念作为别名，目前把外部的文字内容拖拽进已有的摘录只能形成这个摘录的评论，而实际上是希望它作为标题别名的。现阶段AutoTitle只能把符合条件的摘录转成标题，摘录内容只能来自文章内部，能不能单独开发一个插件把符合条件的评论也转换成标题，或者把它整合到现在的AutoTitle里。感谢大神！

**Comment by ourongxing** [comment]
目前 MN 没有提供添加评论的触发器，也就是说插件无法在添加评论的时候自动运行
