### ISSUE TITLE
Feature: Enhanced Regex Engine

### ISSUE THREAD

**Issue by aidenlx** [ourongxing/ohmymn#5]
可以尝试使用[xregexp](https://www.npmjs.com/package/xregexp)替代原生js引擎，有提供兼容层支持negative lookbehide等Safari不支持的高级功能，最后也会编译为原生RegExp对象

**Comment by ourongxing** [comment]
没多大必要，正则用的人不多，就现在提供的这些已经够他们用来自定义了。

**Comment by aidenlx** [comment]
就提一下，看你之前踩到我开发的坑了（Safari的巨坑之一）跟你说下解决方案，太麻烦的话也没多大必要
