### ISSUE TITLE
Feature: Auto Serial Number

### ISSUE THREAD

**Issue by aidenlx** [ourongxing/ohmymn#6]
我这里有一个应[wslldsdh](https://bbs.marginnote.cn/u/wslldsdh)的需求制作的小插件，打开后可以自动添加序列号到标题前，逻辑和功能都已经实现了，你假如有兴趣可以考虑集成进来，代码可以随意使用：[ordered-list](https://github.com/aidenlx/ordered-list)

**Comment by ourongxing** [comment]
目前已经有这个功能了，批量重命名

**Comment by aidenlx** [comment]
另外，假如你有兴趣加进去的话可以考虑在论坛@[wslldsdh](https://bbs.marginnote.cn/u/wslldsdh)一下，他应该也有些想法

**Comment by aidenlx** [comment]
太棒了！之前没细看，主要是我那个是老早写的但没啥动力写文档啥的就搁置在那，想起来跟你提一下，没想到你这做的这么完备了
