### ISSUE TITLE
能否在AutoReplace中实现对标题的同步替换？

### ISSUE THREAD

**Issue by clark874** [ourongxing/ohmymn#7]
作者好，感谢你的工作！目前遇到一个问题，我使用AutoReplace实现了对ocr错误空格在摘录中的替换，但mn中经常存在的另一个操作是选中一段话设为标题，能否让AutoReplace实现对这种操作中错误的替换？谢谢~

**Comment by ourongxing** [comment]
可以打开 anotherautotitle 自动合并摘录的选项，以及 mn 设置里的拖拽选取到脑图自动合并，你会感叹这是多么的美妙。
