### ISSUE TITLE
在Autotitle中保留摘录，用正则表达式提取特定摘录内容作为标题

### ISSUE THREAD

**Issue by clark874** [ourongxing/ohmymn#9]
开发者好，我当前使用时遇到一个问题：我想实现摘录一段中英混合文本时，自动用正则表达式提取英文并形成“英文；”这样的标题，同时也保留摘录。
在Autotitle功能中，我实现了提取英文并形成标题，但不能同时保留摘录。
我希望能够设置一个控制，让用户自主选择是否开启摘录转标题。如果配合正则表达式，实际上可以实现自动提取摘录中特定内容成为标题，这是比直接摘录转标题更高级的功能。
谢谢！

**Comment by ourongxing** [comment]
我正有这个打算，会在参数中加一个特定的字符来决定是否保留摘录，目前在申请签名中，我也打算歇一会，过段时间会开始更新测试版本。
